spring:
  application:
    name: web-app
  profiles:
    # available profiles: echo-agent,  football-agent, apeldoornit-agent, starwars-agent, startrek-agent
    active: football-agent,apeldoornit-agent,starwars-agent,startrek-agent
    default: echo-agent
  ai:
    openai:
      chat:
        model: "gpt-5-mini"
      api-key: ${OPENAI_API_KEY:web-app-default-api-key}

logging:
  level:
    org.rag4j.chatter: INFO
