spring:
  application:
    name: Agentic Chatter Web App
  ai:
    openai:
      chat:
        model: "gpt-5-mini"
      api-key: ${OPENAI_API_KEY:web-app-default-api-key}

logging:
  level:
    org.rag4j.chatter: INFO
    org.rag4j.chatter.agents: DEBUG
moderator:
  loop-alternations-threshold: 4
  agent-cooldown: 1
conversation:
  max-agent-depth: 4